$( function() {
    var availableTags = [
        "Center for Ethics and Entrepreneurship Gardner-Webb",
        "Yan P. Lin Centre: Freedom & Global Orders in Ancient & Modern Worlds",
        "Institute for Technology, Law and Policy",
        "Ciocca Center for Principled Entrepreneurship",
        "Ciocca Center for Business, Ethics, and Society",
        "Colloquium for the Advancement of Free-Enterprise Education",
        "Keenan Center for Entrepreneurship",
        "Stephen S. Smith Center",
        "Western Resources Legal Center",
        "Center for Advancing Opportunity",
        "PPE Program at Villanova University",
        "PPE Program at Bowling Green State University",
        "Hernando de Soto Capital Markets Program",
        "California Center for the Study of the Economics of Innovation and Entrepreneurship",
        "International Development Program",
        "Institute for Regulatory Law and Economics",
        "Regulatory Studies Center - The George Washington University",
        "Program in Law, Science, and Technology",
        "Religious Liberty Clinic",
        "Ciocca Center for Principled Entreprenuership",
        "Menard Family Midwest Initiative for Economic Engagement and Research",
        "James C. Bonbright Center for the Study of Regulation",
        "Program for the Study of Midwest Markets and Entrepreneurship",
        "Institute for the Study of Free Enterprise Oklahoma",
        "Academy on Capitalism and Limited Government Foundation",
        "Center for the Study of Government and the Individual",
        "Free Market Institute",
        "Clemson Institute for the Study of Capitalism",
        "Matthew Ryan Center for the Study of Free Institutions and the Public Good",
        "Center for Economics and the Environment/ Hammond Institute for Free Enterprise",
        "Center for the History of Political Economy",
        "Henry Salvatori Center for the Study of Individual Freedom in the Modern World",
        "Center for Economic Education and Financial Literacy",
        "Croft Institute",
        "Center for Economic Education and Financial Literacy",
        "Center for Markets, Ethics, and Entrepreneurship",
        "Center for Political Thought and Leadership",
        "Center for Free Market Studies",
        "Hammond Institute for Free Enterprise",
        "Center for the Study of Public Choice and Private Enterprise",
        "Institute for Justice Research and Development",
        "Martha E. Church Center for Community & Civic Engagement",
        "Center for the Philosophy of Freedom Arizona",
        "Center for the Study of Economic Liberty",
        "Institute for an Entrepreneurial Society",
        "Georgetown Institute for the Study of Markets and Ethics",
        "Program in Corporate Welfare Studies",
        "New Civil Liberties Alliance",
        "Menard Center for Constitutional Studies",
        "Center for Innovation and Entrepreneurship George Mason",
        "University of Pittsburgh/Graduate School of Public and International Affairs",
        "The Center for Economic Education",
        "University of California, Berkeley - Terner Center for Housing Innovation",
        "Markets and Morality",
        "Salem Center for Policy",
        "Gilliam Center for Free Enterprise and Ethical Leadership",
        "Research Group on Constitutional Studies",
        "Center for Public Choice and Market Process",
        "Vernon Smith Center for Experimental Economics",
        "U-Imagine Center",
        "Entrepreneurial Innovation Academy",
        "Beatrice Institute",
        "Center for Law, Religion and Public Policy",
        "Initiative for the Study of Markets",
        "Norman Miller Center for Peace, Justice, and Public Understanding",
        "Center for Engaged Religious Pluralism",
        "Digital Markets Initiative",
        "Weinert Center for Entrepreneurship",
        "Coleman P. Burke Center for Environmental Law",
        "John A. Ryan Institute",
        "Mays Innovation Research Center",
        "Criminal Justice Reform Initiative",
        "Lumen Christi Institute",
        "Center for Public Private Partnerships in Health",
        "Center for Citizenship & Constitutional Government",
        "Phil Smith Center for Free Enterprise",
        "Center for Strategic Studies",
        "Center for Innovation in the Digital Age",
        "Harvard Initiative for Learning and Teaching",
        "Knight First Amendment Institute",
        "Weidenbaum Center on the Economy, Government and Public Policy",
        "Institute for Market Studies",
        "Nebraska Governance and Technology Center",
        "Center for Supply Chain Research",
        "Stephenson Entrepreneurship Institute",
        "L. Charles Hilton Jr. Center for the Study of Economic Prosperity and Individual Opportunity",
        "Economic Science Institute",
        "Legatum Center for Development Entrepreneurship",
        "National School of Public Administration - Brazil",
        "Peter J. Werth Institute for Entrepreneurship & Innovation",
        "Center for Executive Succession",
        "Institute for the Study of Economic Growth",
        "New Haven Economic Performance Laboratory",
        "Oxford Case Centre for Public Leadership",
        "Gwartney Institute for Freedom, Justice and Human Flourishing",
        "The Center for Justice Research",
        "Center for Economic Education",
        "Manuel H. Johnson Center for Political Economy",
        "Baker Institute for Public Policy: Center for Public Finance",
        "Free Enterprise Center, Concordia-Chicago",
        "Academy for Justice Center",
        "Blockchain Innovation Hub",
        "Natural Resource Users Law and Policy Center",
        "Vinson Centre for Liberal Economics and Entrepreneurship",
        "Center for Responsible Citizenship",
        "center for politics and governance",
        "1889 Institute",
        "Calgary Center TBD Name",
        "The Freedom Project",
        "Liberty and Law Center",
        "Center for the Study of Statesmanship",
        "Center for the Analysis of Property Rights and Innovation",
        "Mackenzie Center for Economic Freedom",
        "Center for Research on the Wisconsin Economy (CROWE)",
        "NYU Center for Social Media and Politics",
        "Urban Entrepreneurship and Policy Institute",
        "Benedictine College - Center for Constitutional Liberty",
        "MSU Initiative for Regulation and Applied Economic Analysis",
        "Center for Innovation",
        "Smith- Tocqueville Center for Studies in Political Economy",
        "Kellogg Institute for International Studies",
        "Open Source Economics Laboratory",
        "McNair Institute for Entrepreneurism and Free Enterprise",
        "Bagwell Center for the Study of Markets and Economic Opportunity",
        "University of Pennsylvania/International Relations Program",
        "Amy Rees Anderson Entrepreneurship Institute",
        "Program in Constitutional Studies",
        "Space, Cyber, and Telecommunications Law Program",
        "Challey Institute",
        "Center for Public Policy Analysis",
        "John Dickinson Forum for the Study of America's Founding Principles.",
        "Remedium eXchange",
        "Free Speech Project",
        "Center for Ethics in Society",
        "McNair Center for Entrepreneurship and Economic Growth",
        "BB&T Center for Economic Education and Policy Studies",
        "Institute of Political Economy",
        "Center for Free Enterprise West Virginia",
        "Alliance Bank Economic Policy Institute",
        "Center for Faith and Flourishing",
        "Initiative and Referendum Institute",
        "Transactional Records Access Clearinghouse",
        "Center for Protection of Intellectual Property",
        "The Rose Institute of State and Local Government",
        "Lodestar Dispute Resolution Center",
        "Immigration Policy Lab",
        "Center for Governance and Markets",
        "Center for Great Books and Human Flourishing",
        "Center for Entrepreneurship and Innovation Grove City",
        "Criminal Justice Innovation Lab",
        "Duree Center for Entrepreneurship",
        "Newman Institute for Catholic Thought and Culture",
        "Center for the Science of Moral Understanding",
        "Center for Competition Policy",
        "Centro para la Libre Competencia",
        "The McNair Center for Free Enterprise & Entrepreneurship",
        "Founder Central Initiative",
        "Faith and Liberty Institute",
        "William & Mary Center for the Study of Law and Markets",
        "Institute for Economic Inquiry",
        "Center for Free Enterprise Florida Southern",
        "Furman Center",
        "Political Economy and Environmental Research Initiative",
        "Law and Economics Center",
        "Political Economy Research Institute at Middle Tennessee State University",
        "Baker Institute for Public Policy",
        "Devoe L. Moore Center",
        "Department of Education Reform",
        "Center for the Study of Liberal Democracy",
        "Becker Friedman Institute",
        "Center for Economic History",
        "Drug Enforcement and Policy Center",
        "Institute for Human Ecology",
        "Smith Institute for Political Economy and Philosophy",
        "Koch Center for Leadership and Ethics",
        "Program on Education Policy and Governance",
        "Center for an Informed Public",
        "Babson Center for Global Commerce",
        "Center for Free Enterprise Concordia Wisconsin",
        "Howard H. Baker Jr. Center for Public Policy",
        "Hernando DeSoto Capital Markets Program",
        "Adam Smith Center for Economic Freedom",
        "Eudaimonia Institute",
        "Knee Center for the Study of Occupational Regulation",
        "Center for Law & Liberty",
        "Purdue University Research Center in Economics",
        "Quattrone Center for the Fair Administration of Justice",
        "Private Enterprise Research Center",
        "O'Niel Center for Global Markets and Freedom",
        "BB&T Center for the Study of the Moral Foundations of Capitalism",
        "Technology and Policy Research Initiatives",
        "First Amendment Center",
        "Braniff Classical Education Graduate Program",
        "Center for Free Enterprise Louisville",
        "Technology & Policy Research Initiative",
        "Institute for Advanced Studies in Culture",
        "Centro de Innovación y Liderazgo",
        "Clemson University/John E. Walker Department of Economics",
        "Charles Widger School of Law",
        "Program on Educational Pluralism",
        "The Center for State Policy Analysis (cSPA) / Tisch College, Tufts University",
        "The Notre Dame International Security Center",
        "School of Civil and Economic Thought and Leadership",
        "John F. Baugh Center for Entrepreneurship",
        "The Deason Criminal Justice Reform Center",
        "Institute for the Study of Free Enterprise Kentucky",
        "Center Name TBD",
        "Institute for the Study of Political Economy",
        "Liberty and Ethics Center",
        "Center focused on Innovation/ Entreprenuership",
        "Arkansas Center for Research in Economics",
        "Program on Economics and Privacy",
        "Center for Educational Opportunity",
        "Center for Grand Strategy",
        "Stephenson Institute for Classical Liberalism",
        "University of North Texas - Economics Research Group",
        "Center for Communication and Civic Renewal",
        "The Center for Informed Democracy and Social Cyber-Security (IDeaS)",
        "Catholic Entrepreneurship & Design Experience",
        "Institute for Data, Democracy, and Politics",
        "Center for Information, Technology, & Public Life",
        "National Agricultural Law Center",
        "Philosophy, Politics, Economics and Law Program",
        "Center for the Study of Economics and Liberty",
        "Political Theory Project",
        "Program in Philosophy, Politics, and Economics",
        "Ed Snider Center for Enterprise and Markets",
        "Wheaton Center for Faith & Innovation",
        "Marriner S. Eccles Institute for Economics and Qualitative Analysis",
        "Political Economy Project",
        "Forcht Center for Entrepreneurship",
        "Blackstone and Burke Center for Law and Liberty",
        "Center for Growth and Opportunity",
        "Friedrich Hayek Center for the Business of Prosperity",
        "Center for Global Business",
        "Wilson Center for Science and Justice",
        "Program on Grand Strategy, Security, and Statecraft",
        "Shelby Cullom Davis Endowment Fund",
        "Chicago Crime Lab",
        "Innovation Lab",
        "Center for Peace and Security Studies",
        "The Center for the History of Liberty",
        "Global Antitrust Institute",
        "The Center for Political and Economic Thought",
        "Gus A. Stavros Center at Florida State University",
        "Center for Education Policy Research",
        "Supply Chain Management Research Center",
        "Center for the Study of Social Change, Institutions and Policy",
        "Center for the Study of Market Alternatives",
        "Education Economics Center",
        "Center for Law, Science and Innovation",
        "Liberty Initiative",
        "Adams Center for Entrepreneurship",
        "Bowen Center for Health Workforce Research and Policy - Indiana University School of Medicine",
        "Computational Justice Lab",
        "Institute for Corruption Studies",
        "Center for the Study of Free Enterprise",
        "Center for Ethics, Economics, and Public Policy",
        "Center Name TBD - James Collins",
        "Stigler Center for the Study of the Economy and the State",
        "Public Utility Research Center",
        "Center for Western Civilization, Thought, and Policy",
        "C. Boyden Gray Center for the Study of the Administrative State",
        "Brandmeyer Center for Applied Economics",
        "Think Tanks and Civil Societies Program",
        "School of Information",
        "Center for the Study of Economic Mobility",
        "Center for the Study of Institutions and Innovation",
        "Troesh Center for Entrepreneurship and Innovation",
        "Center for Entrepreneurship and Business Innovation",
        "Center for Entrepreneurship and Innovation Tulsa",
        "McNair Center for Aerospace Innovation and Research",
        "Kinder Institute for the Study of Constitutional Democracy",
        "John F. Baugh Center for Entrepreneurship and Free Enterprise",
        "American Center for Political Leadership",
        "Classical Liberal Institute",
        "Space, Cyber, & Telecom Law Program",
        "The Science of Ethics Project"   
    ];
   
    $("[fs-field-validation-name='University Center'] > input").autocomplete({
    source: availableTags,
      minLength : 3
});
    
  } );