$( function() {
    var availableTags = [
"1889 Institute",
      "Academy for Justice Center",
      "Academy on Capitalism and Limited Government Foundation",
      "Adam Smith Center for Economic Freedom",
      "Adams Center for Entrepreneurship",
      "Alliance Bank Economic Policy Institute",
      "American Center for Political Leadership",
      "Amy Rees Anderson Entrepreneurship Institute",
      "Arkansas Center for Research in Economics",
      "Babson Center for Global Commerce",
      "Bagwell Center for the Study of Markets and Economic Opportunity",
      "Baker Institute for Public Policy",
      "Baker Institute for Public Policy: Center for Public Finance",
      "BB&T Center for Economic Education and Policy Studies",
      "BB&T Center for the Study of the Moral Foundations of Capitalism",
      "Beatrice Institute",
      "Becker Friedman Institute",
      "Benedictine College - Center for Constitutional Liberty",
      "Blackstone and Burke Center for Law and Liberty",
      "Blockchain Innovation Hub",
      "Bowen Center for Health Workforce Research and Policy - Indiana University School of Medicine",
      "Brandmeyer Center for Applied Economics",
      "Braniff Classical Education Graduate Program",
      "Bridwell Institute",
      "C. Boyden Gray Center for the Study of the Administrative State",
      "California Center for the Study of the Economics of Innovation and Entrepreneurship",
      "Catholic Entrepreneurship & Design Experience",
      "Center focused on Innovation/ Entreprenuership",
      "Center for Advancing Opportunity",
      "Center for an Informed Public",
      "Center for Citizenship & Constitutional Government",
      "Center for Communication and Civic Renewal",
      "Center for Competition Policy",
      "Center for Economic Education",
      "Center for Economic Education and Financial Literacy",
      "Center for Economic History",
      "Center for Economics and the Environment/ Hammond Institute for Free Enterprise",
      "Center for Education Policy Research",
      "Center for Educational Opportunity",
      "Center for Engaged Religious Pluralism",
      "Center for Entrepreneurship and Business Innovation",
      "Center for Entrepreneurship and Innovation Grove City",
      "Center for Entrepreneurship and Innovation Tulsa",
      "Center for Ethics and Entrepreneurship Gardner-Webb",
      "Center for Ethics in Society",
      "Center for Ethics, Economics, and Public Policy",
      "Center for Executive Succession",
      "Center for Faith and Flourishing",
      "Center for Free Enterprise Concordia Wisconsin",
      "Center for Free Enterprise Florida Southern",
      "Center for Free Enterprise Louisville",
      "Center for Free Enterprise West Virginia",
      "Center for Free Market Studies",
      "Center for Global Business",
      "Center for Governance and Markets",
      "Center for Grand Strategy",
      "Center for Great Books and Human Flourishing",
      "Center for Growth and Opportunity",
      "Center for Information, Technology, & Public Life",
      "Center for Innovation",
      "Center for Innovation and Entrepreneurship George Mason",
      "Center for Innovation in the Digital Age",
      "Center for Law & Liberty",
      "Center for Law, Religion and Public Policy",
      "Center for Law, Science and Innovation",
      "Center for Markets, Ethics, and Entrepreneurship",
      "Center for Peace and Security Studies",
      "Center for Political Thought and Leadership",
      "Center for Politics and Governance",
      "Center for Protection of Intellectual Property",
      "Center for Public Choice and Market Process",
      "Center for Public Policy Analysis",
      "Center for Public Private Partnerships in Health",
      "Center for Research on the Wisconsin Economy (CROWE)",
      "Center for Responsible Citizenship",
      "Center for Strategic Studies",
      "Center for Supply Chain Research",
      "Center for the Analysis of Property Rights and Innovation",
      "Center for the History of Political Economy",
      "Center for the Philosophy of Freedom Arizona",
      "Center for the Science of Moral Understanding",
      "Center for the Study of Capitalism",
      "Center for the Study of Economic Liberty",
      "Center for the Study of Economic Mobility",
      "Center for the Study of Economics and Liberty",
      "Center for the Study of Free Enterprise",
      "Center for the Study of Government and the Individual",
      "Center for the Study of Institutions and Innovation",
      "Center for the Study of Liberal Democracy",
      "Center for the Study of Market Alternatives",
      "Center for the Study of Public Choice and Private Enterprise",
      "Center for the Study of Reflective Citizenship",
      "Center for the Study of Social Change, Institutions and Policy",
      "Center for the Study of Statesmanship",
      "Center for Western Civilization, Thought, and Policy",
      "Centro de Innovación y Liderazgo",
      "Centro para la Libre Competencia",
      "Challey Institute",
      "Charles Widger School of Law",
      "Chicago Crime Lab",
      "Cincinnatus Center",
      "Ciocca Center for Business, Ethics, and Society",
      "Ciocca Center for Principled Entrepreneurship",
      "Classical Liberal Institute",
      "Clemson Institute for the Study of Capitalism",
      "Clemson University/John E. Walker Department of Economics",
      "Coleman P. Burke Center for Environmental Law",
      "Colloquium for the Advancement of Free-Enterprise Education",
      "Computational Justice Lab",
      "Cornell Program in Infrastructure Policy",
      "Criminal Justice Innovation Lab",
      "Criminal Justice Reform Initiative",
      "Croft Institute",
      "Department of Education Reform",
      "Devoe L. Moore Center",
      "Digital Markets Initiative",
      "Drug Enforcement and Policy Center",
      "Duree Center for Entrepreneurship",
      "Economic Science Institute",
      "Ed Snider Center for Enterprise and Markets",
      "Education Economics Center",
      "Entrepreneurial Innovation Academy",
      "Eudaimonia Institute",
      "Faith and Liberty Institute",
      "First Amendment Center",
      "Forcht Center for Entrepreneurship",
      "Founder Central Initiative",
      "Free Enterprise Center, Concordia-Chicago",
      "Free Market Institute",
      "Free Speech Project",
      "Friedrich Hayek Center for the Business of Prosperity",
      "Furman Center",
      "Georgetown Institute for the Study of Markets and Ethics",
      "Gilliam Center for Free Enterprise and Ethical Leadership",
      "Global Antitrust Institute",
      "Gus A. Stavros Center at Florida State University",
      "Gwartney Institute for Freedom, Justice and Human Flourishing",
      "Hammond Institute for Free Enterprise",
      "Hannah Arendt Center for Politics and Humanities at Bard College",
      "Harvard Initiative for Learning and Teaching",
      "Henry Salvatori Center for the Study of Individual Freedom in the Modern World",
      "Hernando de Soto Capital Markets Program",
      "Howard H. Baker Jr. Center for Public Policy",
      "Immigration Policy Lab",
      "Initiative and Referendum Institute",
      "Initiative for the Study of Markets",
      "Innovation Lab",
      "Institute for Advanced Studies in Culture",
      "Institute for an Entrepreneurial Society",
      "Institute for Corruption Studies",
      "Institute for Data, Democracy, and Politics",
      "Institute for Human Ecology",
      "Institute for Justice Research and Development",
      "Institute for Market Studies",
      "Institute for Regulatory Law and Economics",
      "Institute for Technology, Law and Policy",
      "Institute for the Study of Economic Growth",
      "Institute for the Study of Free Enterprise Kentucky",
      "Institute for the Study of Free Enterprise Oklahoma",
      "Institute for the Study of Political Economy",
      "Institute of Political Economy",
      "International Development Program",
      "James C. Bonbright Center for the Study of Regulation",
      "Jean Beer Blumenfeld Center for Ethics",
      "John A. Ryan Institute",
      "John Dickinson Forum for the Study of America's Founding Principles",
      "John F. Baugh Center for Entrepreneurship and Free Enterprise",
      "Keenan Center for Entrepreneurship",
      "Kellogg Institute for International Studies",
      "Kinder Institute for the Study of Constitutional Democracy",
      "Knee Center for the Study of Occupational Regulation",
      "Knight First Amendment Institute",
      "Koch Center for Leadership and Ethics",
      "L. Charles Hilton Jr. Center for the Study of Economic Prosperity and Individual Opportunity",
      "Law and Economics Center",
      "Legatum Center for Development Entrepreneurship",
      "Liberty and Ethics Center",
      "Liberty and Law Center",
      "Liberty Initiative",
      "Lloyd Greif Center for Entrepreneurial Studies",
      "Lodestar Dispute Resolution Center",
      "Lumen Christi Institute",
      "Mackenzie Center for Economic Freedom",
      "Manuel H. Johnson Center for Political Economy",
      "Markets and Morality",
      "Marriner S. Eccles Institute for Economics and Qualitative Analysis",
      "Martha E. Church Center for Community & Civic Engagement",
      "Matthew Ryan Center for the Study of Free Institutions and the Public Good",
      "Mays Innovation Research Center",
      "McNair Center for Aerospace Innovation and Research",
      "McNair Center for Entrepreneurship and Economic Growth",
      "McNair Institute for Entrepreneurism and Free Enterprise",
      "Menard Center for Constitutional Studies",
      "Menard Family Institute for Economic Inquiry",
      "Menard Family Midwest Initiative for Economic Engagement and Research",
      "MSU Initiative for Regulation and Applied Economic Analysis",
      "National Agricultural Law Center",
      "National School of Public Administration - Brazil",
      "Natural Resource Users Law and Policy Center",
      "Nebraska Governance and Technology Center",
      "New Civil Liberties Alliance",
      "New Haven Economic Performance Laboratory",
      "Newman Institute for Catholic Thought and Culture",
      "Norman Miller Center for Peace, Justice, and Public Understanding",
      "NYU Center for Social Media and Politics",
      "O'Niel Center for Global Markets and Freedom",
      "Open Source Economics Laboratory",
      "Oxford Case Centre for Public Leadership",
      "Peter J. Werth Institute for Entrepreneurship & Innovation",
      "Phil Smith Center for Free Enterprise",
      "Philosophy, Politics, Economics and Law Program",
      "Political Economy and Environmental Research Initiative",
      "Political Economy Project",
      "Political Economy Research Institute at Middle Tennessee State University",
      "Political Theory Project",
      "PPE Program at Bowling Green State University",
      "PPE Program at Villanova University",
      "Private Enterprise Research Center",
      "Program for the Study of Midwest Markets and Entrepreneurship",
      "Program in Constitutional Studies",
      "Program in Corporate Welfare Studies",
      "Program in Law, Science, and Technology",
      "Program in Philosophy, Politics, and Economics",
      "Program on Economics and Privacy",
      "Program on Education Policy and Governance",
      "Program on Educational Pluralism",
      "Program on Grand Strategy, Security, and Statecraft",
      "Public Utility Research Center",
      "Purdue University Research Center in Economics",
      "Quattrone Center for the Fair Administration of Justice",
      "Regulatory Studies Center - The George Washington University",
      "Religious Liberty Clinic",
      "Remedium eXchange",
      "Research Group on Constitutional Studies",
      "Salem Center for Policy",
      "School of Civil and Economic Thought and Leadership",
      "School of Information",
      "Shelby Cullom Davis Endowment Fund",
      "Smith Institute for Political Economy and Philosophy",
      "Smith- Tocqueville Center for Studies in Political Economy",
      "Space, Cyber, and Telecommunications Law Program",
      "Stephen S. Smith Center",
      "Stephenson Entrepreneurship Institute",
      "Stephenson Institute for Classical Liberalism",
      "Stigler Center for the Study of the Economy and the State",
      "Supply Chain Management Research Center",
      "Technology & Policy Research Initiative",
      "The Ashbrook Center at Ashland University",
      "The Center for Economic Education",
      "The Center for Informed Democracy and Social Cyber-Security (IDeaS)",
      "The Center for Justice Research",
      "The Center for Political and Economic Thought",
      "The Center for State Policy Analysis (cSPA) / Tisch College, Tufts University",
      "The Center for the History of Liberty",
      "The Deason Criminal Justice Reform Center",
      "The Freedom Project",
      "The McNair Center for Free Enterprise & Entrepreneurship",
      "The Notre Dame International Security Center",
      "The Rose Institute of State and Local Government",
      "The Science of Ethics Project",
      "Think Tanks and Civil Societies Program",
      "Transactional Records Access Clearinghouse",
      "Troesh Center for Entrepreneurship and Innovation",
      "U-Imagine Center",
      "University of California, Berkeley - Terner Center for Housing Innovation",
      "University of North Texas - Economics Research Group",
      "University of Pennsylvania/International Relations Program",
      "University of Pittsburgh/Graduate School of Public and International Affairs",
      "Urban Entrepreneurship and Policy Institute",
      "Vernon Smith Center for Experimental Economics",
      "Vinson Centre for Liberal Economics and Entrepreneurship",
      "Weidenbaum Center on the Economy, Government and Public Policy",
      "Weinert Center for Entrepreneurship",
      "Western Resources Legal Center",
      "Wheaton Center for Faith & Innovation",
      "William & Mary Center for the Study of Law and Markets",
      "Wilson Center for Science and Justice",
      "Yan P. Lin Centre: Freedom & Global Orders in Ancient & Modern Worlds"   
    ];
   
    $("[fs-field-validation-name='University Center'] > input").autocomplete({
    source: availableTags,
      minLength : 3
});
    
  } );
